; Format:
; [Code]
; where Code should be in hexdecimal and follow 0xAAAA format in upper case.
;0x0000=Liumoon Test



; Code version: Channel Code Definition_Ver0.1

0x0000=Main Input voltage (V)
0x0001=Main Input voltage R (V)
0x0002=Main Input voltage S (V)
0x0003=Main Input voltage T (V)
0x0004=Main Input voltage RS (V)
0x0005=Main Input voltage ST (V)