; Format:
; [Main_Code]
; Sub_Code=Event Description
; where Main_Code and Sub_Code should be in hexdecimal and follow 0xAAAA or oxAA format in upper case.
;[0xFE30]
;0x01=Jesse Test



; Event code version: DPM Recorder Event Code_Ver0.1

[0xFE20]
0x01=PFC - To Standby Mode

[0xFE22]
0x01=PFC - To AC Mode

[0xFE23]
0x01=PFC - To DC Bus Free Run Mode

[0xFE25]
0x01=PFC - To DC Mode

[0xFE30]
0x01=PFC - Charger Fault


[0xFF20]
0x01=INV - To Standby Mode

[0xFF22]
0x01=INV - To Inverter Ready Mode

[0xFF23]
0x01=INV - To Voltage Mode

[0xFF24]
0x01=INV - To APF Mode

[0xFFFF]
0x00=Test